# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

#pool:
#  vmImage: ubuntu-latest

#steps:
#- script: echo Hello, world!
 # displayName: 'Run a one-line script'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'MyDockerRegistry'
      repository: 'sample-app'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.BuildId)'

  - script: |
      echo "Deploying to Azure VM"
     
      ssh azureuser@$(VM_IP) 'docker pull sample-app && docker run -d -p 80:80 sample-app'
    displayName: 'Deploy to VM'
  

#- script: |
 #   echo Add other tasks to build, test, and deploy your project.
  ##echo See https://aka.ms/yaml
  #displayName: 'Run a multi-line script'